# This is a basic workflow to help you get started with Actions

name: Arti

# Controls when the workflow will run
on: [push]
 
env: 
  ART_NAME: zdrkp
 
jobs:
  # This workflow contains a single job called "build"
  art1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        
      - name: Build ${{ env.ART_NAME }} for ubuntu-latest
        run: go build ${{ env.ART_NAME }}.go 
        
      - name: upload art for linux
        uses: actions/upload-artifact@v1
        with: 
          name: ${{ env.ART_NAME }}
          path: ./${{ env.ART_NAME }}.exe
